default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
  username: tradespace
  password: tradespace

development:
  <<: *default
  database: books_development

test:
  <<: *default
  database: books_test

staging:
  <<: *default
  database: books_staging

production:
  <<: *default
  database: books_staging
