local: &local
  :url: redis://h:pcacc98fqnv69o9qg2o6r86md9i@ec2-23-23-156-130.compute-1.amazonaws.com:21719
  :host: localhost
  :port: 6379
  :timeout: 1
  :inline: true

development: *local

test: *local

production:
  :url: redis://h:pcacc98fqnv69o9qg2o6r86md9i@ec2-23-23-156-130.compute-1.amazonaws.com:21719
